---
- name: Deploy Nagios Plugins
  hosts: all
  become: true
  
  roles:
    - deploy-nagios-checks
  
  post_tasks:
    - name: List installed plugins
      ansible.builtin.command:
        cmd: ls -lh {{ nagios_plugins_install_prefix }}/libexec/
      register: plugins_list
      changed_when: false
      
    - name: Display available plugins
      ansible.builtin.debug:
        var: plugins_list.stdout_lines
